name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          NODE_VERSION: 22.14.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: bun run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/.vitepress/dist --project-name=elysia-doc --branch=production
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: bun
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          NODE_VERSION: 22.14.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
